apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ayiwj1lmm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ayiwj1lmm-python 
  name: ayiwj1lmm-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ayiwj1lmm-python 
